version: '3.3'

# Creating application network
networks:
  laravel-application-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local

services:
  # Configuring pst laravel application

 #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_test
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel_test
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./backend:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-application-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel-test-webserver
    restart: always
    tty: true
    ports:
      - "8888:80"
        #  - "4431:443"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.17
    container_name: matrimonial-assist-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: matrimonial-assist
      MYSQL_ROOT_PASSWORD: 123456@Mat
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network